name: Generate Release
on:
    workflow_call:
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout last 500 commits (for <commits> to work)
              uses: actions/checkout@v4
              with:
                  fetch-depth: 500

            - name: Get Target
              id: get-target
              run: |
                  TARGET="${{ github.ref }}"
                  TARGET="${TARGET##*/}"
                  if [ "$TARGET" = "main" ]; then
                    TARGET="stable"
                  fi
                  echo "target=$TARGET" >> $GITHUB_OUTPUT

            - name: Generate Release Text
              id: generate-release
              run: |
                  python3 ./.github/workflows/changelog.py \
                    "${{ steps.get-target.outputs.target }}" \
                    ./output.env ./changelog.md --workdir . }}"
                  source ./output.env
                  echo "title=${TITLE}" >> $GITHUB_OUTPUT
                  echo "tag=${TAG}" >> $GITHUB_OUTPUT

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ steps.generate-release.outputs.title }}
                  tag_name: ${{ steps.generate-release.outputs.tag }}
                  body_path: ./changelog.md
                  make_latest: ${{ steps.get-target.outputs.target == 'stable' }}
                  prerelease: ${{ steps.get-target.outputs.target != 'stable' }}
