name: Generate Release
on:
    workflow_call:
        inputs:
            release_date:
                required: true
                type: string
            tag_date:
                required: true
                type: string
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-release:
        runs-on: ubuntu-latest
        steps:
            - name: Get Latest Tag Version
              id: get_latest_tag
              run: |
                  base_tag=${{ inputs.tag_date }}
                  # Get all tags matching the base tag
                  tags=$(gh api repos/${{ github.repository }}/releases --jq '[.[].tag_name | select(startswith("'"${base_tag}"'"))] | sort_by(.)')
                  if [ -z "$tags" ] || [ "$tags" == "[]" ]; then
                      echo "version=${base_tag}" >> $GITHUB_OUTPUT
                  else
                      # Get the latest version number
                      latest=$(echo "$tags" | jq -r '.[-1]')
                      if [[ $latest == $base_tag ]]; then
                      echo "version=${base_tag}.1" >> $GITHUB_OUTPUT
                      else

                      # Extract the number after the dot and increment it
                      num=$(echo $latest | awk -F. '{print $2}')
                      next=$((num + 1))
                      echo "version=${base_tag}.${next}" >> $GITHUB_OUTPUT
                      fi
                  fi
              env:
                  GITHUB_TOKEN: ${{ github.token }}

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  name: ${{ steps.get_latest_tag.outputs.version }}
                  body: |
                      ## Release Information
                      - **Image Name**: `${{ github.event.repository.name }}`
                      - **Build Date**: `${{ inputs.release_date }}`
                      - **Registry**: https://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}

                      ## Tags
                      - `latest`
                      - `${{ steps.get_latest_tag.outputs.version }}`
                  tag_name: ${{ steps.get_latest_tag.outputs.version }}
                  make_latest: true
                  draft: false
                  prerelease: false
